### ISSUE TITLE
Meteor 1.2.0.2 upgrade

### ISSUE THREAD

**Issue by louis49** [Sanjo/meteor-karma#10]
After upgrading Meteor to 1.2.0.2, the package was updated to sanjo:karma@3.0.2 that break execution of unit server tests with this message : 

E20150929-18:12:31.413(2) (webapp.js:709) Error running template: TypeError: Cannot read property 'DiffSequence' of undefined

Setting sanjo:karma@1.7.0 and sanjo:jasmine@0.19.1 resolve the issue.

**Comment by Sanjo** [comment]
Was there no stack trace on the error message? Have you tried sanjo:jasmine@0.20.0? Server unit mode is disable in this version. Maybe that gets rid of the error.
